### PR TITLE
debug button

### LINKED ISSUE #227: add debug button to the transaction line

### PR DESCRIPTION
**Pull request by LianaHus**
fixes https://github.com/ethereum/mix/issues/227

### CODE REVIEW

**Comment by chriseth** [comment]
Clicking the button does not work for me.

**Comment by LianaHus** [comment]
strange. I'll check

**Comment by chriseth** [comment]
It is not a real button, right? So there is no "press" effect. But I guess that is ok for now.

**Comment by LianaHus** [comment]
@chriseth  I can change that if you want

**Pull request merged**
